### ISSUE TITLE
azure-pipelines.yml is missing the three most recent Ghidra versions

### ISSUE THREAD

**Issue by Neo-Desktop** [cmu-sei/pharos#159]
```yaml
      ghidra922:
        ghidraUrl: "https://ghidra-sre.org/ghidra_9.2.2_PUBLIC_20201229.zip"
        ghidraVersion: "9.2.2"
      ghidra921:
        ghidraUrl: "https://ghidra-sre.org/ghidra_9.2.1_PUBLIC_20201215.zip"
        ghidraVersion: "9.2.1"
      ghidra92:
        ghidraUrl: "https://ghidra-sre.org/ghidra_9.2_PUBLIC_20201113.zip"
        ghidraVersion: "9.2"
```

The above yaml hould be inserted in `azure-pipelines.yml` after line 90

I can open a pull request accompanying this ticket if requested
